# Generated by Django 5.0.6 on 2024-07-03 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_price_purchase_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_time',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='total_price',
        ),
        migrations.AddField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 2, 23, 13, 43, 925181)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='direccion',
            field=models.CharField(default='Dirección por defecto', max_length=255),
        ),
        migrations.AddField(
            model_name='purchase',
            name='email',
            field=models.EmailField(default='email@ejemplo.com', max_length=254),
        ),
        migrations.AddField(
            model_name='purchase',
            name='nombre',
            field=models.CharField(default='Nombre por defecto', max_length=100),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
