# Generated by Django 5.0.6 on 2024-07-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_purchase_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='email',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_data',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='total',
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user_email',
            field=models.EmailField(default='ejemplo@ejemplo.cl', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='user_name',
            field=models.CharField(default='Anónimo', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
