# Generated by Django 5.0.6 on 2024-07-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_purchase_direccion_remove_purchase_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='user_address',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='user_name',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_data',
            field=models.JSONField(default='null'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
