# Generated by Django 5.0.6 on 2024-07-03 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_purchase_options_alter_purchase_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
