# Generated by Django 5.0.6 on 2024-07-03 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_created_at_purchase_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
